//
//  GeneratedExtensions.h
//  This file is generated by the TSStyleManager application
//  http://www.touchwonders.com
//  Generation date: Feb 12, 2012 17:13:04 
//

#import <Foundation/Foundation.h>

/**
 * UIColor category using user defined styles
 */
@interface UIColor (_StyleExtension)

/** greenish color */
+(UIColor *)Greenish;

/** dark red color */
+(UIColor *)DarkRed;

/** dark gray color */
+(UIColor *)DarkGray;

@end

/**
 * UIFont category using user defined styles
 */
@interface UIFont (_StyleExtension)

/** This is the Zapfino font, size 35 */
+(UIFont *)Zapfino35;

/** This is the Calibri Italic font, size 40 */
+(UIFont *)CalibriItalic40;

/** This is the MyriadPro-Regular font, size 33 */
+(UIFont *)MyriadProRegular33;

/** Search for alternative fonts when the font cannot be found */
+(UIFont *)searchForAlternativesWithName:(NSString *)fontName andSize:(int)size;
@end


/**
 * TSShadow class
 *
 * This container holds information about the shadow to be used with a label
 */
@interface TSShadow : NSObject
@property (nonatomic, strong) UIColor *shadowColor;
@property (nonatomic, assign) CGSize shadowOffset;

/** (null) */
+(TSShadow *)WhiteRightShadow;

/** white shadow at the top (emboss-like) */
+(TSShadow *)WhiteTopShadow;

/** red shadow on the right of the text */
+(TSShadow *)RedRightShadow;

/** This is my first shadow */
+(TSShadow *)DarkBottomShadow;

@end


/**
 * TSStyle class
 *
 * This class describes the style of a UILabel. Used in combination with a UILabel category
 */
@interface TSStyle : NSObject
@property (nonatomic, strong) UIFont *font;
@property (nonatomic, strong) UIColor *color;
@property (nonatomic, strong) TSShadow *shadow;

/** This is my first style */
+(TSStyle *)style1;

/** second style */
+(TSStyle *)style2;

/** this is the third and currently last style */
+(TSStyle *)style3;

@end


/**
 * UILabel category using user defined styles
 */
@interface UILabel (_StyleExtension)

/** Return a UILabel with user defined style elements */
-(id)initWithFrame:(CGRect)frame 
          andColor:(UIColor *)color 
           andFont:(UIFont *)font 
         andShadow:(TSShadow *)shadow;

/** Return a UILabel with a user defined style */
-(id)initWithFrame:(CGRect)frame andStyle:(TSStyle *)style;

@end
